const assert=require('node:assert/strict');
const base=process.env.TEST_URL||'http://localhost:3000';
const stamp=Date.now();
function client(){let cookie='';return async(path,method='GET',body)=>{const multipart=body instanceof FormData,headers={cookie};if(!multipart)headers['content-type']='application/json';const response=await fetch(`${base}/api${path}`,{method,headers,body:body?(multipart?body:JSON.stringify(body)):undefined});const set=response.headers.get('set-cookie');if(set)cookie=set.split(';')[0];const type=response.headers.get('content-type')||'';return {status:response.status,data:type.includes('json')?await response.json():await response.arrayBuffer()}}}
async function ok(call,path,method,body){const result=await call(path,method,body);assert.ok(result.status>=200&&result.status<300,`${path}: ${JSON.stringify(result.data)}`);return result.data}
async function uploadDocuments(call){for(const kind of ['driver_license','vehicle_registration']){const form=new FormData();form.set('kind',kind);form.set('document',new Blob([Buffer.from([137,80,78,71,13,10,26,10])],{type:'image/png'}),`${kind}.png`);await ok(call,'/vehicle/documents','POST',form)}}
(async()=>{
 const requester=client(),stranger=client(),driver=client(),replacementDriver=client(),admin=client();
 await ok(requester,'/register','POST',{name:'Requester',email:`r-${stamp}@example.test`,phone:'01700000000',password:'test-password-123'});
 await ok(stranger,'/register','POST',{name:'Stranger',email:`s-${stamp}@example.test`,phone:'01700000001',password:'test-password-123'});
 await ok(driver,'/register','POST',{name:'Driver',email:`d-${stamp}@example.test`,phone:'01800000000',password:'test-password-123',role:'driver'});
 await ok(driver,'/vehicle','PUT',{plate:`LIVE-${stamp}`,kind:'Advanced',location:'Dhaka',equipment:'Oxygen',serviceArea:'Dhaka North',crew:'Driver and paramedic',capacity:1,description:'Test ambulance'});
 await uploadDocuments(driver);
 await ok(replacementDriver,'/register','POST',{name:'Replacement Driver',email:`d2-${stamp}@example.test`,phone:'01800000001',password:'test-password-123',role:'driver'});
 await ok(replacementDriver,'/vehicle','PUT',{plate:`BACKUP-${stamp}`,kind:'Basic',location:'Dhaka',equipment:'First aid',serviceArea:'Dhaka Central',crew:'Driver',capacity:1,description:'Backup ambulance'});
 await uploadDocuments(replacementDriver);
 await ok(admin,'/login','POST',{email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});
 const vehicle=(await ok(admin,'/admin/vehicles')).vehicles.find(v=>v.plate===`LIVE-${stamp}`);
 const replacement=(await ok(admin,'/admin/vehicles')).vehicles.find(v=>v.plate===`BACKUP-${stamp}`);
 assert.equal(vehicle.document_count,2);
 const documents=(await ok(admin,`/admin/vehicles/${vehicle.id}/documents`)).documents;
 assert.equal(documents.length,2);
 assert.equal((await stranger(`/documents/${documents[0].id}`)).status,404);
 assert.equal((await driver(`/documents/${documents[0].id}`)).status,200);
 assert.equal((await driver('/vehicle/availability','PATCH',{available:1})).status,403);
 await ok(admin,`/admin/vehicles/${vehicle.id}`,'PATCH',{approved:1});
 await ok(admin,`/admin/vehicles/${replacement.id}`,'PATCH',{approved:1});
 await ok(driver,'/vehicle/availability','PATCH',{available:1});
 await ok(replacementDriver,'/vehicle/availability','PATCH',{available:1});
 assert.equal((await ok(requester,`/vehicles/${vehicle.id}`)).vehicle.service_area,'Dhaka North');
 assert.ok((await ok(requester,'/vehicles?q=Dhaka&kind=Advanced')).vehicles.some(v=>v.id===vehicle.id));
 assert.equal((await ok(requester,'/vehicles?q=Dhaka&kind=Basic')).vehicles.some(v=>v.id===vehicle.id),false);
 const {id}=await ok(requester,'/requests','POST',{pickup:'Dhanmondi',destination:'Hospital',phone:'01700000000'});
 assert.equal((await stranger(`/requests/${id}/events`)).status,404);
 assert.equal((await stranger(`/requests/${id}/status`,'PATCH',{status:'cancelled'})).status,403);
 await ok(admin,`/requests/${id}/status`,'PATCH',{status:'assigned',vehicle_id:vehicle.id});
 assert.equal((await admin(`/requests/${id}/reassign`,'POST',{vehicle_id:replacement.id})).status,400);
 await ok(admin,`/requests/${id}/reassign`,'POST',{vehicle_id:replacement.id,reason:'Original vehicle reported a mechanical issue'});
 assert.equal((await replacementDriver('/vehicle','PUT',{plate:`BACKUP-${stamp}`,kind:'Basic',location:'Dhaka',equipment:'First aid',serviceArea:'Dhaka Central',capacity:1})).status,409);
 assert.equal((await admin(`/requests/${id}/status`,'PATCH',{status:'assigned',vehicle_id:vehicle.id})).status,409);
 assert.equal((await admin(`/admin/vehicles/${replacement.id}`,'PATCH',{approved:0})).status,409);
 await ok(replacementDriver,`/requests/${id}/status`,'PATCH',{status:'accepted'});
 await ok(replacementDriver,`/requests/${id}/location`,'PUT',{latitude:23.7465,longitude:90.376});
 assert.equal((await ok(requester,`/requests/${id}/location`)).location.latitude,23.7465);
 assert.equal((await stranger(`/requests/${id}/location`)).status,404);
 for(const status of ['en_route','arrived','onboard','completed'])await ok(replacementDriver,`/requests/${id}/status`,'PATCH',{status});
 assert.equal((await ok(requester,`/requests/${id}/location`)).location,null);
 assert.equal((await ok(requester,`/requests/${id}/events`)).events.length,8);
 assert.equal((await ok(requester,`/requests/${id}/events`)).events.some(e=>e.status==='reassigned'&&e.note.includes('mechanical')),true);
 const declined=await ok(requester,'/requests','POST',{pickup:'Gulshan',destination:'Clinic',phone:'01700000000'});
 await ok(admin,`/requests/${declined.id}/status`,'PATCH',{status:'assigned',vehicle_id:vehicle.id});
 assert.equal((await driver(`/requests/${declined.id}/status`,'PATCH',{status:'declined'})).status,400);
 await ok(driver,`/requests/${declined.id}/status`,'PATCH',{status:'declined',reason:'Vehicle requires maintenance'});
 assert.equal((await ok(requester,'/requests')).requests.find(r=>r.id===declined.id).status,'requested');
 assert.equal((await ok(requester,`/requests/${declined.id}/events`)).events.at(-1).note,'Vehicle requires maintenance');
 const cancelled=await ok(requester,'/requests','POST',{pickup:'Banani',destination:'Hospital',phone:'01700000000'});
 assert.equal((await requester(`/requests/${cancelled.id}/status`,'PATCH',{status:'cancelled'})).status,400);
 await ok(requester,`/requests/${cancelled.id}/status`,'PATCH',{status:'cancelled',reason:'Transport no longer needed'});
 assert.equal((await ok(requester,'/requests')).requests.find(r=>r.id===cancelled.id).cancellation_reason,'Transport no longer needed');
 const notices=await ok(requester,'/notifications');
 assert.ok(notices.unread>=1);
 assert.ok(notices.notifications.some(n=>n.status==='completed'));
 await ok(requester,'/notifications/read','POST',{ids:notices.notifications.map(n=>n.id)});
 assert.equal((await ok(requester,'/notifications')).unread,0);
 assert.equal((await requester('/me/password','POST',{currentPassword:'wrong',newPassword:'new-password-123'})).status,403);
 await ok(requester,'/me/password','POST',{currentPassword:'test-password-123',newPassword:'new-password-123'});
 assert.equal((await requester('/me')).data.user,null);
 assert.equal((await requester('/login','POST',{email:`r-${stamp}@example.test`,password:'test-password-123'})).status,401);
 await ok(requester,'/login','POST',{email:`r-${stamp}@example.test`,password:'new-password-123'});
 const recovery=await ok(requester,'/password/forgot','POST',{email:`r-${stamp}@example.test`});
 assert.ok(recovery.resetUrl);
 const resetToken=new URL(recovery.resetUrl).hash.split('token=')[1];
 await ok(requester,'/password/reset','POST',{token:resetToken,password:'recovered-password-123'});
 assert.equal((await requester('/me')).data.user,null);
 assert.equal((await requester('/password/reset','POST',{token:resetToken,password:'another-password-123'})).status,400);
 assert.equal((await requester('/login','POST',{email:`r-${stamp}@example.test`,password:'new-password-123'})).status,401);
 await ok(requester,'/login','POST',{email:`r-${stamp}@example.test`,password:'recovered-password-123'});
 const unknown=await ok(stranger,'/password/forgot','POST',{email:`unknown-${stamp}@example.test`});
 assert.equal(unknown.resetUrl,undefined);
 console.log('PASS: roles, dispatch, reasons, location privacy, lifecycle, notifications, password change and recovery');
})().catch(error=>{console.error(error);process.exitCode=1});
